services:
  hejminformoj:
    build: ./streamlit
    ports:
      - "7610:8501"
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - .env
    command: streamlit run /app/home.py
  db:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env